item {
  id: 1
  name: 'agac'
}

item {
  id: 2
  name: 'araba'
}

item {
  id: 3
  name: 'bisiklet'
}

item {
  id: 4
  name: 'insan'
}

item {
  id: 5
  name: 'kedi'
}

item {
  id: 6
  name: 'kirmizi yaya isik'
}

item {
  id: 7
  name: 'kopek'
}

item {
  id: 8
  name: 'levha'
}

item {
  id: 9
  name: 'motosiklet'
}

item {
  id: 10
  name: 'yaya gecidi'
}

item {
  id: 11
  name: 'yesil yaya isik'
}

